# features/win_rate_21d/constants.py
"""Locked constants for win_rate_21d.

======================================================================
Human-maintained governance constants.  NOT auto-generated.
======================================================================

All values in this module are governance-locked.  Any value change MUST be
accompanied by the corresponding SD amendment or spec version bump.  This
file MUST NOT be regenerated by any script; every edit here is a
deliberate governance action.

Traceability convention:
    Every governance-locked constant carries an inline source comment
    directly above the value.  The convention is:

        # {SOURCE} [{STATUS}] [at {COMMIT}]

    where SOURCE is one of: SD-A2-1..11, SPEC_LOCKED §X.Y, A2-GOV-1..4,
    N-A2-5-1..8, N-A2-8-1..10.

Grep-friendly listing of all governance references:

    grep -E '^# (SD-A2-|SPEC_LOCKED|A2-GOV-|N-A2-)' constants.py
"""

from typing import Final, Literal

# ─────────────────────────────────────────────────────────────
# Numerical constants
# ─────────────────────────────────────────────────────────────

# SPEC_LOCKED v0.1.0 §3.6 (spec commit 1cf8365)
WINDOW: Final[int] = 21

# SPEC_LOCKED v0.1.0 §3.6 (spec commit 1cf8365)
MIN_OBS: Final[int] = 15

# SD-A2-1 LOCKED at 93a8317
# Governance: no post-hoc adjustment permitted; see SD-A2-1 rider
# and spec §3.7.  Change requires spec amendment.
MIN_CROSS_SECTION_OBS_PER_DATE: Final[int] = 30

# ─────────────────────────────────────────────────────────────
# Identity constants (SD-A2-2)
# ─────────────────────────────────────────────────────────────

# SD-A2-2 LOCKED at 50c093e
PRODUCER_TABLE_NAME: Final[str] = "win_rate_21d_cross_section_median"

# SD-A2-2 LOCKED at 50c093e
# BASE TABLE target per spec §5.1.
DUCKDB_PATH: Final[str] = "data/_storage/helios.duckdb"

# SPEC_LOCKED v0.1.0 (spec commit 1cf8365)
FEATURE_ID: Final[str] = "win_rate_21d"

# ─────────────────────────────────────────────────────────────
# Build strategy (SD-A2-3)
# ─────────────────────────────────────────────────────────────

# SD-A2-3 LOCKED at 40c0cd1
# See producer.py module docstring for full strategy discussion.
# Any function suggesting incremental semantics (build_incremental,
# build_since, update, patch, merge_into, append_new_dates) is FORBIDDEN
# and enforced by test_no_forbidden_names.py.
BUILD_STRATEGY: Final[Literal["one_shot_full_rebuild"]] = (
    "one_shot_full_rebuild"
)

# ─────────────────────────────────────────────────────────────
# Manifest schema version (SD-A2-5)
# ─────────────────────────────────────────────────────────────

# SD-A2-5 N-A2-5-6 LOCKED at 23b249b
MANIFEST_SCHEMA_VERSION: Final[str] = "1.0.0"

# ─────────────────────────────────────────────────────────────
# Hash-length constants (Issue C)
# ─────────────────────────────────────────────────────────────

# Human-maintained.  Not governance-locked in the SD chain; these encode
# the hex string lengths of standard hash outputs and exist to eliminate
# magic numbers from regex construction in manifest.py.

# Length of a hex-encoded SHA-1 digest (current git default).
SHA1_HEX_LEN: Final[int] = 40

# Length of a hex-encoded SHA-256 digest (canonical content_hash per SD-A2-5;
# also the future git object hash after upstream SHA-256 transition).
SHA256_HEX_LEN: Final[int] = 64